### ISSUE TITLE
Bug: applyChanges / setAtPath - Error: Cannot set a value directly

### ISSUE THREAD

**Issue by codeart1st** [LegendApp/legend-state#298]
```
TypeError: 'set' on proxy: trap returned falsish for property '***'
    at setAtPath (helpers.ts:85:16)
    at applyChange (helpers.ts:224:12)
    at applyChanges (helpers.ts:228:17)
    at channel.onmessage (state.ts:35:3)
```

https://github.com/LegendApp/legend-state/blob/3a7ba8c06c973fa4fd8d72a521c68a0fcb1a246a/src/helpers.ts#L85

**Comment by codeart1st** [comment]
applyChanges is not for observable. Didn't saw the typings definition, sorry.
