### ISSUE TITLE
TypeError: targetChild.set is not a function

### ISSUE THREAD

**Issue by pruge** [LegendApp/legend-state#407]
Hi 

When I update block$, the error occurs.
However, if I update except transform, there will be no error.

How should I modify transform?

I have the following state:
```ts
export const block$ = observable(
  syncedCrud({
    list: listModel<Block>({
      model: 'block',
      where: () => ({ hmiProjectId: hmiProjectStore$.projectId.get() }),
    }),
    create: createModel<Block>({
      model: 'block',
      relation: () => ({ hmiProject: { connect: { id: hmiProjectStore$.projectId.get() } } }),
    }),
    update: updateModel<Block>({ model: 'block' }),
    delete: deleteModel<Block>({ model: 'block' }),

    updatePartial: true,
    as: 'object',
    mode: 'assign',

    transform: {
      load: async (value: Block): Promise<BlockLocal> => {
        const blockLocal = { ...value, node: null } as BlockLocal
        blockLocal.node = parse(value.component, options)
        return blockLocal
      },
      save: async (value: BlockLocal): Promise<Block> => {
        delete value.node
        delete value.hmiProjectId
        console.log('save', value)
        return value
      },
    },
)
```

```ts
// update position
block$[id].set((prev) => ({ ...prev, ...position }))
```

```ts
app-index.js:33 
Forcibly completing observableBatcher because end() was never called. 
This may be due to an uncaught error between begin() and end().

index.mjs:461 
Uncaught (in promise) TypeError: targetChild.set is not a function
    at _mergeIntoObservable (index.mjs:461:25)
    at _mergeIntoObservable (index.mjs:463:11)
    at _mergeIntoObservable (index.mjs:463:11)
    at mergeIntoObservable (index.mjs:432:5)
    at eval (sync.mjs:737:104)
    at onChangeRemote2 (sync.mjs:269:3)
    at doChangeRemote (sync.mjs:737:13)
```

**Comment by pruge** [comment]
The problem does not occur in version [3.0.0-beta.15](https://www.npmjs.com/package/@legendapp/state/v/3.0.0-beta.15).

**Comment by jmeistrich** [comment]
Hi @pruge, is it possible to create a minimal repro that I could test? I'm not sure how to reproduce the error you're seeing.
